# Jupyter Cheat Sheet

## Sample Data
#### Source: https://raw.githubusercontent.com/practical-jupyter/sample-data/master/anime/anime.csv

## Setup

In [45]:
from IPython.display import Markdown as md
import numpy as np
import os
import pandas as pd

## Examples

### Read CSV

In [11]:
anime_csv = os.path.join('data', 'anime.csv')
df = pd.read_csv(anime_csv)
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
10481,34471,Youkai Watch Movie 4,"Comedy, Kids, Supernatural",Movie,1,NaN,169
10482,34284,Yuuki Yuuna wa Yuusha de Aru: Washio Sumi no Shou,"Drama, Fantasy, Magic, Slice of Life",TV,6,NaN,2593
10483,34445,Yuuki Yuuna wa Yuusha de Aru: Yuusha no Shou,"Drama, Fantasy, Magic, Slice of Life",TV,6,NaN,4439
10484,33035,Yuyushiki Special,NaN,Special,1,NaN,2294
10485,33390,Zunda Horizon,NaN,Movie,1,NaN,160

### Derive Column / Top 6 Longest Name

In [29]:
df['name length'] = df['name'].apply(len) # Intentional typo
df['name_length'] = df['name'].apply(len)
df.sort_values('name_length', ascending=False).head(6)

,anime_id,name,genre,type,episodes,rating,members,name_length,name length
8666,33876,Kochira Katsushikaku Kameari Kouenmae Hashutsu...,"Comedy, Police",Special,1,7.29,62,100,100
8671,33881,Kochira Katsushikaku Kameari Kouenmae Hashutsu...,"Comedy, Police",Special,2,7.18,116,100,100
8669,33879,Kochira Katsushikaku Kameari Kouenmae Hashutsu...,"Comedy, Police",Special,2,7.20,100,100,100
8668,33875,Kochira Katsushikaku Kameari Kouenmae Hashutsu...,"Comedy, Police",Special,1,6.95,104,100,100
8664,33882,Kochira Katsushikaku Kameari Kouenmae Hashutsu...,"Comedy, Police",Special,2,7.00,135,100,100
8667,33878,Kochira Katsushikaku Kameari Kouenmae Hashutsu...,"Comedy, Police",Special,1,7.05,101,100,100

### Drop Column

In [30]:
df.drop('name length', axis=1, inplace=True)
df

,anime_id,name,genre,type,episodes,rating,members,name_length
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,14
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,32
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,8
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,11
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,13
...,...,...,...,...,...,...,...,...
10481,34471,Youkai Watch Movie 4,"Comedy, Kids, Supernatural",Movie,1,NaN,169,20
10482,34284,Yuuki Yuuna wa Yuusha de Aru: Washio Sumi no Shou,"Drama, Fantasy, Magic, Slice of Life",TV,6,NaN,2593,49
10483,34445,Yuuki Yuuna wa Yuusha de Aru: Yuusha no Shou,"Drama, Fantasy, Magic, Slice of Life",TV,6,NaN,4439,44
10484,33035,Yuyushiki Special,NaN,Special,1,NaN,2294,17
10485,33390,Zunda Horizon,NaN,Movie,1,NaN,160,13

### Select with Multiple Conditions

In [64]:
df.loc[(df['type'] == 'TV') & (df['rating'] > 9)] # Bracket is mandatory

,anime_id,name,genre,type,episodes,rating,members,name_length
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,32
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,8
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,11
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,13
5,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10,9.15,93351,57
6,11061,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",TV,148,9.13,425855,22
9,15417,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",TV,13,9.11,81109,24
10,4181,Clannad: After Story,"Drama, Fantasy, Romance, Slice of Life, Supern...",TV,24,9.06,456749,20
12,918,Gintama,"Action, Comedy, Historical, Parody, Samurai, S...",TV,201,9.04,336376,7
9785,30120,Spoon-hime no Swing Kitchen,"Adventure, Kids",TV,Unknown,9.60,47,27